# Purpose: Check package build
# Trigger: pull_request

name: CI

on:
  # trigger
  pull_request:
    branches:
      - dev
      - main
    types:
      - opened
      - closed
      - synchronize

#
jobs:
  #
  #
  #
  check:
    # skip if closed PR is "closed without merging (dismissed)"
    if: >
      github.event.action != 'closed' || (
        github.event.action == 'closed' &&
        github.event.pull_request.merged == true
      )

    name: Check

    runs-on: ubuntu-latest

    # job level permissions
    permissions:
      contents: read # for actions/checkout

    steps:
      # 1
      - name: Checkout the repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      # 2. to provide access to setup-node's `cache: pnpm`
      - name: Setup PNPM
        uses: pnpm/action-setup@v5
        with:
          version: 10.x.x
          run_install: false
          cache: true

      # 3
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml # root lockfile

      # 4. prevent when lockfile is out of sync
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # 5
      - name: Check types, lint and formatting
        run: pnpm check

      # 6
      - name: Check build
        run: pnpm build
